config/routes.rb
Rails.application.routes.draw do
  resources :pictures
  resources :aviarys,  only: [:index], as: :cute_dog 
  root 'application#home'
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def picture_url
    image.url(:thumb)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/aviarys_controller.rb
class AviarysController < ApplicationController

  def index
  render :index
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
  
  end

  def new

  end

  def create

  end

  def edit

  end

  def update

  end

  def show

  end

  def destroy

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
Welcome

<%= link_to (image_tag("IMG_4610.JPG")), '/pictures' %>


<!-- <BGSOUND id="BGSOUND_ID" LOOP=3 SRC="app/assets/audio/dog_call.wav">

<script type="text/javascript" language="JavaScript">

var playSound = function(audioURL) {
  if (document.all) document.all['BGSOUND_ID'].src=audioURL;
  else self.iplayer.location.replace('jsplayer.htm?'+audioURL);
}

</script>

<form name=myform>
  <input type=button value="Play Sound" onClick="playSound('dog_call.wav')">
</form> -->




<!-- // <script charset="utf-8">
// filepicker.setKey("AbZiS4ISpQTa7F9uoQdFiz");
// filepicker.pickAndStore({},{},function(Blobs){
//     return JSON.stringify(Blobs);
// });
// // // var x = filepicker.pick(
// // //   function(y){
// // //     console.log(y.url);
// // //   }
// // // );
// // // filepicker.store(
// // //   x,
// // //   {path: '/'}
// // // );
//  </script>
// <! <a download="test.jpg" href="https://www.google.com/images/srpr/logo11w.png">Testing</a>
// <form action="/pictures" method="get">
//
//   <input type="file" capture="camera" accept="image/*" id="cameraInput" name="cameraInput">
//   <input type="submit" value="Submit File">
//
// </form> -->

app/views/aviarys/index.html.erb
HOLA

<img id="editableimage1" src="https://www.filepicker.io/api/file/VXis26wHSMu4a0Kr42DA" alt="" />

<!-- Instantiate the widget -->
<script type="text/javascript">

var featherEditor = new Aviary.Feather({
  apiKey: "<%= ENV["AVIARY"] %>",
  apiVersion: 3,
  tools: 'all',
  onSave: function(imageID, newURL) {
    var img = document.getElementById(imageID);
    img.src =newURL;
  },

});

function launchEditor(id, src) {
  featherEditor.launch({
    image: "editableimage1",
    url: "https://www.filepicker.io/api/file/VXis26wHSMu4a0Kr42DA"
  });
  return false;
}

</script>

<a href="https://www.filepicker.io/api/file/VXis26wHSMu4a0Kr42DA" onclick="return launchEditor('editableimage1',
'https://www.filepicker.io/api/file/VXis26wHSMu4a0Kr42DA');">CUTEIFY YOUR DOG!!</a>

app/views/edit/index.html.erb
MUFASA

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Super Dog App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="//api.filepicker.io/v1/filepicker.js"></script>
  <script type="text/javascript" src="http://feather.aviary.com/js/feather.js"></script>
  <!-- <javascript_include_tag 'jquery-1.11.1.js', 'data-turbolinks-track' => true %> -->
  <script charset="utf-8" type="text/javascript" src="assets/javascripts/jquery-1.11.1.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<output></output>

<%= form_for @picture do |f| %>
  <%= f.file_field :image, accept: 'image/*', id: 'capture', capture: 'camera' %>
  <p>
    <%= f.submit :'Upload', id:"save", class:"primary-button" %>
  </p>
<% end %>



<!--
<script>
  $(function() {
    $('form').on('submit', function(e) {
      if ($('output').children().length === 1) {
        return true;
      } else if ($('img').length > 0) {
        return true
      } else {
        e.preventDefault();
        $('<div class="validation-error">Please choose a file!</div>').prependTo('.add-image').hide().slideDown()
        setTimeout(function(){
          $('.validation-error').slideToggle(577, function() {
            $(this).remove()
          });
        }, 3777);
        return false;
      };
    });
    var $current_image = $('#current_image');
    var $pictureImage = $('#picture_image');
    $pictureImage.trigger('change');
    $pictureImage.on('change', function(event){
      var file = event.target.files[0];
      $current_image.remove();
      if (file.type.match('image.*')){
        var reader = new FileReader();
        reader.onload = (function(theFile){
          var img = new Image();
          img.src = theFile.target.result;
          var $output = $('output');
          $output.html(img);
        });
        reader.readAsDataURL(file);
      }
    });
    var $form = $('form');
    $form.submit(function(){
      $.each(params, function(i, param){
        $('<input />').attr('type', 'hidden')
        .attr('name', param.name)
        .attr('value', param.value)
        .appendTo($form);
      });
    });
  });
</script> -->

app/views/pictures/edit.html.erb
<div class="body">
  <h1 class="heading">Edit this image!</h1>
  <div class="add-image">
    <%= image_tag @clothing_item.image.url(:medium), :id => "current_image" %>

    <%= render partial: 'form' %>
  </div>
</div> 

app/views/pictures/index.html.erb
<%= link_to(cute_dog_index_path) %>

<audio loop id="dog_call" class="audio_player" preload="auto" autoplay=true>
  <source src='dog_call.wav' type="audio/wav">
</audio>
<img src="" alt="">

<script charset="utf-8">
filepicker.setKey("<%= ENV["FILEPICKER_API"] %>");
filepicker.pick(
  {service: ['WEBCAM']},
  function(Blob){
    console.log(Blob.url);
    url = Blob.url;
  }
);

var elem = document.getElementsByClassName('btn btn-primary btn-large')

elem.onclick = function previewFile() {
  var preview = document.querySelector('img');
  var file    = document.querySelector('video').files[0];
  var reader  = new FileReader();

  reader.onloadend = function () {
    preview.src = reader.result;
  }

  if (file) {
    reader.readAsDataURL(file);
  } else {
    preview.src = "";
  }
}



</script>



<!-- https://www.filepicker.io/api/file/VXis26wHSMu4a0Kr42DA","filename":"snap.jpg","mimetype":"image/jpeg","size":28208,"isWriteable":true}] -->

<!-- [{"url":"https://www.filepicker.io/api/file/Y4mfdN8TTH2dDyhEf9UP","filename":"snap.jpg","mimetype":"image/jpeg","size":28208,"isWriteable":true}]
pictures:33 undefined -->

<!-- INSERT BUTTON INSTEAD? -->

<!-- <form action="<%= cute_dog_index_path %>" method="get">
<input type="file" capture="camera" accept="image/*" id="cameraInput" name="cameraInput">
<input type="submit" value="Submit File">
 </form> -->

<!-- // <script>
//   $.each($('dog_call'), function () {
//     this.stop();
//   });
// </script> -->


<!-- // <script charset="utf-8">
// var showPicture = document.querySelector("cameraInput");
// // Get window.URL object
// var URL = window.URL || window.webkitURL;
//
// // Create ObjectURL
// var imgURL = URL.createObjectURL(file);
//
// // Set img src to ObjectURL
// showPicture.src = imgURL;
//
// // For performance reasons, revoke used ObjectURLs
// URL.revokeObjectURL(imgURL);
// </script> -->

<!-- // <script>
// filepicker.setKey("AbZiS4ISpQTa7F9uoQdFiz");
// // var y = document.getElementById("cameraInput");
// filepicker.pick(
//   function(y){
//     console.log(y.url);
//   }
//
// filepicker.store(c, {path: '/'})
// );
// // filepicker.store($('input'),{path: 'Desktop/'});
// </script> -->
<!-- <img id="editableimage1" src="https://www.petfinder.com/wp-content/uploads/2012/11/122163343-conditioning-dog-loud-noises-632x475.jpg"/>

<script type='text/javascript'>
var featherEditor = new Aviary.Feather({
  apiKey: 'your-key-here',
  apiVersion: 3,
  theme: 'dark', // Check out our new 'light' and 'dark' themes!
  tools: 'all',
  appendTo: '',
  onSave: function(imageID, newURL) {
    var img = document.getElementById(imageID);
    img.src = newURL;
  },
  onError: function(errorObj) {
    alert(errorObj.message);
  }
});
function launchEditor(id, src) {
  featherEditor.launch({
    image: id,
    url: src
  });
  return false;
}
</script> -->

app/views/pictures/new.html.erb
<div class="body">
  <h1 class="heading">YOUR DOG</h1>
  <div class="add-image">
    <%= render partial: 'form' %>
  </div>
</div>

app/views/pictures/show.html.erb
<div class="body cf">
  <div class="show-image">  
    <div class="col1">
      <%= image_tag @picture.image.url(:medium) %>      
    </div>
    
    <div class="col2">
      <%= button_to("Edit this image!", edit_picture_path(@picture), method: :get, 'class' => 'edit secondary-button') %>
      <%= link_to('or delete it from your gallery', picture_path(@clothing_item), method: :delete, 'class' => 'delete', data: { confirm: 'Are you sure?' }) %><br>
    </div>
  </div>
</div>  